<a href="https://colab.research.google.com/github/davism02/Project-4-Predicting-Hospial-Readmission-for-Diabetes/blob/main/diabetes_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
url ='https://raw.githubusercontent.com/davism02/Project-4-Predicting-Hospial-Readmission-for-Diabetes/main/Resources/diabetic_data.csv'

In [85]:
#Loading libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [86]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

In [87]:
df = pd.read_csv(url)
df.head()

   encounter_id  patient_nbr             race  ... change diabetesMed readmitted
0       2278392      8222157        Caucasian  ...     No          No         NO
1        149190     55629189        Caucasian  ...     Ch         Yes        >30
2         64410     86047875  AfricanAmerican  ...     No         Yes         NO
3        500364     82442376        Caucasian  ...     Ch         Yes         NO
4         16680     42519267        Caucasian  ...     Ch         Yes         NO

[5 rows x 50 columns]

In [88]:
# Include only the interested features

df = df.iloc[:, [2,3,4,5,9,22,41,48, 49]]

df.head()

              race  gender      age  ... insulin  diabetesMed readmitted
0        Caucasian  Female   [0-10)  ...      No           No         NO
1        Caucasian  Female  [10-20)  ...      Up          Yes        >30
2  AfricanAmerican  Female  [20-30)  ...      No          Yes         NO
3        Caucasian    Male  [30-40)  ...      Up          Yes         NO
4        Caucasian    Male  [40-50)  ...  Steady          Yes         NO

[5 rows x 9 columns]

In [89]:
#Checking for missing values in dataset
#In the dataset missing values are represented as '?' sign
for col in df.columns:
    if df[col].dtype == object:
         print(col,df[col][df[col] == '?'].count())

race 2273
gender 0
age 0
weight 98569
max_glu_serum 0
insulin 0
diabetesMed 0
readmitted 0

In [90]:
# Drop rows with invalid values (?)

df = df[(df.race != "?") & (df.gender != "?") & (df.age != "?") & (df.weight != "?")]

df

                   race  gender      age  ... insulin  diabetesMed readmitted
1102          Caucasian    Male  [50-60)  ...  Steady          Yes        >30
1132          Caucasian  Female  [60-70)  ...  Steady          Yes        >30
1136          Caucasian  Female  [40-50)  ...  Steady          Yes         NO
1190          Caucasian  Female  [70-80)  ...  Steady          Yes         NO
1204          Caucasian  Female  [80-90)  ...  Steady          Yes        >30
...                 ...     ...      ...  ...     ...          ...        ...
101456  AfricanAmerican    Male  [60-70)  ...      No           No        >30
101516        Caucasian    Male  [60-70)  ...      No          Yes        >30
101640        Caucasian  Female  [70-80)  ...  Steady          Yes         NO
101667        Caucasian    Male  [70-80)  ...      No          Yes        <30
101723        Caucasian    Male  [60-70)  ...      No          Yes        >30

[3059 rows x 9 columns]

In [91]:
# Convert readmitted column to binary field

df = df.replace({'readmitted': {">30": 0, "NO": 0, "<30": 1}})

df

                   race  gender      age  ... insulin  diabetesMed readmitted
1102          Caucasian    Male  [50-60)  ...  Steady          Yes          0
1132          Caucasian  Female  [60-70)  ...  Steady          Yes          0
1136          Caucasian  Female  [40-50)  ...  Steady          Yes          0
1190          Caucasian  Female  [70-80)  ...  Steady          Yes          0
1204          Caucasian  Female  [80-90)  ...  Steady          Yes          0
...                 ...     ...      ...  ...     ...          ...        ...
101456  AfricanAmerican    Male  [60-70)  ...      No           No          0
101516        Caucasian    Male  [60-70)  ...      No          Yes          0
101640        Caucasian  Female  [70-80)  ...  Steady          Yes          0
101667        Caucasian    Male  [70-80)  ...      No          Yes          1
101723        Caucasian    Male  [60-70)  ...      No          Yes          0

[3059 rows x 9 columns]

In [92]:
#Checking data types of each variable
df.dtypes

race                object
gender              object
age                 object
weight              object
time_in_hospital     int64
max_glu_serum       object
insulin             object
diabetesMed         object
readmitted           int64
dtype: object

In [93]:
# Determine the number of unique values in each column.
df.nunique()

race                 4
gender               2
age                 10
weight               9
time_in_hospital    14
max_glu_serum        1
insulin              4
diabetesMed          2
readmitted           2
dtype: int64

In [94]:
df = df.drop(['max_glu_serum'], axis = 1)

In [95]:
df.to_csv("final_data.csv")

In [96]:
# Convert categorical data to numeric with `pd.get_dummies`
df = pd.get_dummies(df,dtype=float)
df.head()

      time_in_hospital  readmitted  ...  diabetesMed_No  diabetesMed_Yes
1102                 2           0  ...             0.0              1.0
1132                 5           0  ...             0.0              1.0
1136                 3           0  ...             0.0              1.0
1190                11           0  ...             0.0              1.0
1204                 9           0  ...             0.0              1.0

[5 rows x 33 columns]

In [97]:
# Split our preprocessed data into our features and target arrays
y = df['readmitted'].values
y

array([0, 0, 0, ..., 0, 1, 0])

In [98]:
# Split the preprocessed data into a training and testing dataset
X = df.drop('readmitted', axis=1).values
X

array([[2., 0., 0., ..., 0., 0., 1.],
       [5., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [8., 0., 0., ..., 0., 0., 1.],
       [4., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.]])

In [99]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state= 42)

In [100]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [101]:
# Compile, Train and Evalutate the Model

In [102]:
## Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 231

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 21)                315

 dense_3 (Dense)             (None, 1)                 22

=================================================================
Total params: 680
Trainable params: 680
Non-trainable params: 0
_________________________________________________________________

In [103]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [104]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
61/61 [==============================] - 1s 7ms/step - loss: 0.5777 - accuracy: 0.7871 - val_loss: 0.4129 - val_accuracy: 0.8986
Epoch 2/100
61/61 [==============================] - 0s 4ms/step - loss: 0.4057 - accuracy: 0.8810 - val_loss: 0.3407 - val_accuracy: 0.8986
Epoch 3/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3846 - accuracy: 0.8810 - val_loss: 0.3337 - val_accuracy: 0.8986
Epoch 4/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3771 - accuracy: 0.8810 - val_loss: 0.3309 - val_accuracy: 0.8986
Epoch 5/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3714 - accuracy: 0.8810 - val_loss: 0.3292 - val_accuracy: 0.8986
Epoch 6/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3682 - accuracy: 0.8810 - val_loss: 0.3276 - val_accuracy: 0.8986
Epoch 7/100
61/61 [==============================] - 0s 4ms/step - loss: 0.3647 - accuracy: 0.8810 - val_loss: 0.3264 - val_accuracy: 0.8986
Epoch 8/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3628 - accuracy: 0.8810 - val_loss: 0.3263 - val_accuracy: 0.8986
Epoch 9/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3603 - accuracy: 0.8810 - val_loss: 0.3259 - val_accuracy: 0.8986
Epoch 10/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3589 - accuracy: 0.8810 - val_loss: 0.3274 - val_accuracy: 0.8986
Epoch 11/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3574 - accuracy: 0.8810 - val_loss: 0.3282 - val_accuracy: 0.8986
Epoch 12/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3552 - accuracy: 0.8810 - val_loss: 0.3283 - val_accuracy: 0.8986
Epoch 13/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3545 - accuracy: 0.8810 - val_loss: 0.3278 - val_accuracy: 0.8986
Epoch 14/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3534 - accuracy: 0.8810 - val_loss: 0.3278 - val_accuracy: 0.8986
Epoch 15/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3521 - accuracy: 0.8810 - val_loss: 0.3289 - val_accuracy: 0.8986
Epoch 16/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3511 - accuracy: 0.8810 - val_loss: 0.3297 - val_accuracy: 0.8986
Epoch 17/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3492 - accuracy: 0.8810 - val_loss: 0.3302 - val_accuracy: 0.8986
Epoch 18/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3493 - accuracy: 0.8810 - val_loss: 0.3299 - val_accuracy: 0.8986
Epoch 19/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3481 - accuracy: 0.8810 - val_loss: 0.3302 - val_accuracy: 0.8986
Epoch 20/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3472 - accuracy: 0.8810 - val_loss: 0.3302 - val_accuracy: 0.8986
Epoch 21/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3452 - accuracy: 0.8810 - val_loss: 0.3294 - val_accuracy: 0.8986
Epoch 22/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3451 - accuracy: 0.8810 - val_loss: 0.3292 - val_accuracy: 0.8986
Epoch 23/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3442 - accuracy: 0.8810 - val_loss: 0.3298 - val_accuracy: 0.8986
Epoch 24/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3433 - accuracy: 0.8810 - val_loss: 0.3294 - val_accuracy: 0.8986
Epoch 25/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3424 - accuracy: 0.8810 - val_loss: 0.3298 - val_accuracy: 0.8986
Epoch 26/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3413 - accuracy: 0.8810 - val_loss: 0.3298 - val_accuracy: 0.8986
Epoch 27/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3410 - accuracy: 0.8810 - val_loss: 0.3288 - val_accuracy: 0.8986
Epoch 28/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3398 - accuracy: 0.8810 - val_loss: 0.3309 - val_accuracy: 0.8986
Epoch 29/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3394 - accuracy: 0.8810 - val_loss: 0.3306 - val_accuracy: 0.8986
Epoch 30/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3381 - accuracy: 0.8810 - val_loss: 0.3299 - val_accuracy: 0.8986
Epoch 31/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3380 - accuracy: 0.8810 - val_loss: 0.3306 - val_accuracy: 0.8986
Epoch 32/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3372 - accuracy: 0.8820 - val_loss: 0.3304 - val_accuracy: 0.8986
Epoch 33/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3370 - accuracy: 0.8820 - val_loss: 0.3308 - val_accuracy: 0.8986
Epoch 34/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3364 - accuracy: 0.8820 - val_loss: 0.3307 - val_accuracy: 0.8986
Epoch 35/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3367 - accuracy: 0.8810 - val_loss: 0.3296 - val_accuracy: 0.8986
Epoch 36/100
61/61 [==============================] - 0s 4ms/step - loss: 0.3351 - accuracy: 0.8825 - val_loss: 0.3323 - val_accuracy: 0.8986
Epoch 37/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3339 - accuracy: 0.8830 - val_loss: 0.3318 - val_accuracy: 0.8986
Epoch 38/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3332 - accuracy: 0.8830 - val_loss: 0.3299 - val_accuracy: 0.8986
Epoch 39/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3332 - accuracy: 0.8820 - val_loss: 0.3315 - val_accuracy: 0.8986
Epoch 40/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3328 - accuracy: 0.8830 - val_loss: 0.3297 - val_accuracy: 0.8986
Epoch 41/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3313 - accuracy: 0.8830 - val_loss: 0.3351 - val_accuracy: 0.8957
Epoch 42/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3310 - accuracy: 0.8835 - val_loss: 0.3319 - val_accuracy: 0.8986
Epoch 43/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3309 - accuracy: 0.8840 - val_loss: 0.3322 - val_accuracy: 0.8986
Epoch 44/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3294 - accuracy: 0.8846 - val_loss: 0.3331 - val_accuracy: 0.8986
Epoch 45/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3285 - accuracy: 0.8840 - val_loss: 0.3332 - val_accuracy: 0.8986
Epoch 46/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3281 - accuracy: 0.8846 - val_loss: 0.3342 - val_accuracy: 0.8986
Epoch 47/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3267 - accuracy: 0.8851 - val_loss: 0.3328 - val_accuracy: 0.8986
Epoch 48/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3265 - accuracy: 0.8840 - val_loss: 0.3339 - val_accuracy: 0.8957
Epoch 49/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3260 - accuracy: 0.8840 - val_loss: 0.3327 - val_accuracy: 0.8986
Epoch 50/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3245 - accuracy: 0.8846 - val_loss: 0.3390 - val_accuracy: 0.8986
Epoch 51/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3252 - accuracy: 0.8846 - val_loss: 0.3323 - val_accuracy: 0.8986
Epoch 52/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3232 - accuracy: 0.8851 - val_loss: 0.3322 - val_accuracy: 0.9014
Epoch 53/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3224 - accuracy: 0.8866 - val_loss: 0.3320 - val_accuracy: 0.9014
Epoch 54/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3226 - accuracy: 0.8856 - val_loss: 0.3334 - val_accuracy: 0.8986
Epoch 55/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3227 - accuracy: 0.8846 - val_loss: 0.3340 - val_accuracy: 0.8986
Epoch 56/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3207 - accuracy: 0.8856 - val_loss: 0.3333 - val_accuracy: 0.8986
Epoch 57/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3203 - accuracy: 0.8866 - val_loss: 0.3331 - val_accuracy: 0.8986
Epoch 58/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3194 - accuracy: 0.8866 - val_loss: 0.3348 - val_accuracy: 0.8986
Epoch 59/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3191 - accuracy: 0.8871 - val_loss: 0.3331 - val_accuracy: 0.8986
Epoch 60/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3182 - accuracy: 0.8866 - val_loss: 0.3323 - val_accuracy: 0.8986
Epoch 61/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3181 - accuracy: 0.8856 - val_loss: 0.3338 - val_accuracy: 0.8986
Epoch 62/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3179 - accuracy: 0.8861 - val_loss: 0.3328 - val_accuracy: 0.8986
Epoch 63/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3170 - accuracy: 0.8866 - val_loss: 0.3317 - val_accuracy: 0.8986
Epoch 64/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3163 - accuracy: 0.8866 - val_loss: 0.3329 - val_accuracy: 0.8986
Epoch 65/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3159 - accuracy: 0.8861 - val_loss: 0.3288 - val_accuracy: 0.8986
Epoch 66/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3144 - accuracy: 0.8861 - val_loss: 0.3302 - val_accuracy: 0.8986
Epoch 67/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3142 - accuracy: 0.8856 - val_loss: 0.3311 - val_accuracy: 0.8986
Epoch 68/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3143 - accuracy: 0.8881 - val_loss: 0.3311 - val_accuracy: 0.8957
Epoch 69/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3144 - accuracy: 0.8866 - val_loss: 0.3324 - val_accuracy: 0.8957
Epoch 70/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3136 - accuracy: 0.8876 - val_loss: 0.3341 - val_accuracy: 0.8957
Epoch 71/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3132 - accuracy: 0.8881 - val_loss: 0.3349 - val_accuracy: 0.8957
Epoch 72/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3115 - accuracy: 0.8887 - val_loss: 0.3292 - val_accuracy: 0.8986
Epoch 73/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3121 - accuracy: 0.8892 - val_loss: 0.3298 - val_accuracy: 0.8957
Epoch 74/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3107 - accuracy: 0.8871 - val_loss: 0.3329 - val_accuracy: 0.8928
Epoch 75/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3106 - accuracy: 0.8881 - val_loss: 0.3310 - val_accuracy: 0.8957
Epoch 76/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3104 - accuracy: 0.8897 - val_loss: 0.3300 - val_accuracy: 0.8957
Epoch 77/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3095 - accuracy: 0.8876 - val_loss: 0.3274 - val_accuracy: 0.8957
Epoch 78/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3098 - accuracy: 0.8887 - val_loss: 0.3295 - val_accuracy: 0.8957
Epoch 79/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3084 - accuracy: 0.8887 - val_loss: 0.3287 - val_accuracy: 0.8957
Epoch 80/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3087 - accuracy: 0.8897 - val_loss: 0.3296 - val_accuracy: 0.8957
Epoch 81/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3076 - accuracy: 0.8897 - val_loss: 0.3320 - val_accuracy: 0.8928
Epoch 82/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3085 - accuracy: 0.8897 - val_loss: 0.3272 - val_accuracy: 0.8957
Epoch 83/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3076 - accuracy: 0.8892 - val_loss: 0.3278 - val_accuracy: 0.8957
Epoch 84/100
61/61 [==============================] - 0s 4ms/step - loss: 0.3071 - accuracy: 0.8892 - val_loss: 0.3311 - val_accuracy: 0.8928
Epoch 85/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3060 - accuracy: 0.8892 - val_loss: 0.3297 - val_accuracy: 0.8928
Epoch 86/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3063 - accuracy: 0.8876 - val_loss: 0.3309 - val_accuracy: 0.8957
Epoch 87/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3062 - accuracy: 0.8887 - val_loss: 0.3315 - val_accuracy: 0.8928
Epoch 88/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3059 - accuracy: 0.8887 - val_loss: 0.3329 - val_accuracy: 0.8928
Epoch 89/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3061 - accuracy: 0.8897 - val_loss: 0.3319 - val_accuracy: 0.8928
Epoch 90/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3058 - accuracy: 0.8892 - val_loss: 0.3351 - val_accuracy: 0.8928
Epoch 91/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3049 - accuracy: 0.8902 - val_loss: 0.3305 - val_accuracy: 0.8957
Epoch 92/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3050 - accuracy: 0.8887 - val_loss: 0.3305 - val_accuracy: 0.8928
Epoch 93/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3043 - accuracy: 0.8892 - val_loss: 0.3334 - val_accuracy: 0.8928
Epoch 94/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3046 - accuracy: 0.8897 - val_loss: 0.3361 - val_accuracy: 0.8928
Epoch 95/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3030 - accuracy: 0.8892 - val_loss: 0.3346 - val_accuracy: 0.8928
Epoch 96/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3022 - accuracy: 0.8892 - val_loss: 0.3333 - val_accuracy: 0.8928
Epoch 97/100
61/61 [==============================] - 0s 4ms/step - loss: 0.3029 - accuracy: 0.8887 - val_loss: 0.3340 - val_accuracy: 0.8928
Epoch 98/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3018 - accuracy: 0.8897 - val_loss: 0.3415 - val_accuracy: 0.8928
Epoch 99/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3047 - accuracy: 0.8871 - val_loss: 0.3341 - val_accuracy: 0.8928
Epoch 100/100
61/61 [==============================] - 0s 3ms/step - loss: 0.3014 - accuracy: 0.8892 - val_loss: 0.3392 - val_accuracy: 0.8899

In [105]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

24/24 - 0s - loss: 0.4096 - accuracy: 0.8889 - 45ms/epoch - 2ms/step
Loss: 0.40955567359924316, Accuracy: 0.8888888955116272

In [106]:
# Export our model to HDF5 file
from google.colab import files

nn.save('/content/Model_1.h5')
files.download('/content/Model_1.h5')